/*
* generated by Xtext
*/
package org.yazgel.aphrodit.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.yazgel.aphrodit.xtext.services.AphroditGrammarAccess;

public class AphroditParser extends AbstractContentAssistParser {
	
	@Inject
	private AphroditGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.yazgel.aphrodit.xtext.ui.contentassist.antlr.internal.InternalAphroditParser createParser() {
		org.yazgel.aphrodit.xtext.ui.contentassist.antlr.internal.InternalAphroditParser result = new org.yazgel.aphrodit.xtext.ui.contentassist.antlr.internal.InternalAphroditParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getSectionElementAccess().getAlternatives(), "rule__SectionElement__Alternatives");
					put(grammarAccess.getMenuElementAccess().getAlternatives(), "rule__MenuElement__Alternatives");
					put(grammarAccess.getRowElementAccess().getAlternatives(), "rule__RowElement__Alternatives");
					put(grammarAccess.getDivisionElementAccess().getAlternatives(), "rule__DivisionElement__Alternatives");
					put(grammarAccess.getCarouselPageElementAccess().getAlternatives(), "rule__CarouselPageElement__Alternatives");
					put(grammarAccess.getCardPageElementAccess().getAlternatives(), "rule__CardPageElement__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getHeaderTypeAccess().getAlternatives(), "rule__HeaderType__Alternatives");
					put(grammarAccess.getAnchorTypeAccess().getAlternatives(), "rule__AnchorType__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getModelAccess().getGroup_3(), "rule__Model__Group_3__0");
					put(grammarAccess.getPageAccess().getGroup(), "rule__Page__Group__0");
					put(grammarAccess.getPageAccess().getGroup_3(), "rule__Page__Group_3__0");
					put(grammarAccess.getPageAccess().getGroup_4(), "rule__Page__Group_4__0");
					put(grammarAccess.getPageAccess().getGroup_5(), "rule__Page__Group_5__0");
					put(grammarAccess.getPageAccess().getGroup_5_3(), "rule__Page__Group_5_3__0");
					put(grammarAccess.getPageAccess().getGroup_6(), "rule__Page__Group_6__0");
					put(grammarAccess.getSectionAccess().getGroup(), "rule__Section__Group__0");
					put(grammarAccess.getSectionAccess().getGroup_4(), "rule__Section__Group_4__0");
					put(grammarAccess.getSectionAccess().getGroup_5(), "rule__Section__Group_5__0");
					put(grammarAccess.getSectionAccess().getGroup_6(), "rule__Section__Group_6__0");
					put(grammarAccess.getSectionAccess().getGroup_7(), "rule__Section__Group_7__0");
					put(grammarAccess.getSectionAccess().getGroup_8(), "rule__Section__Group_8__0");
					put(grammarAccess.getSectionAccess().getGroup_8_3(), "rule__Section__Group_8_3__0");
					put(grammarAccess.getMenuAccess().getGroup(), "rule__Menu__Group__0");
					put(grammarAccess.getMenuAccess().getGroup_4(), "rule__Menu__Group_4__0");
					put(grammarAccess.getMenuAccess().getGroup_5(), "rule__Menu__Group_5__0");
					put(grammarAccess.getMenuAccess().getGroup_6(), "rule__Menu__Group_6__0");
					put(grammarAccess.getMenuAccess().getGroup_7(), "rule__Menu__Group_7__0");
					put(grammarAccess.getMenuAccess().getGroup_8(), "rule__Menu__Group_8__0");
					put(grammarAccess.getMenuAccess().getGroup_8_3(), "rule__Menu__Group_8_3__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getRowAccess().getGroup(), "rule__Row__Group__0");
					put(grammarAccess.getRowAccess().getGroup_4(), "rule__Row__Group_4__0");
					put(grammarAccess.getRowAccess().getGroup_5(), "rule__Row__Group_5__0");
					put(grammarAccess.getRowAccess().getGroup_6(), "rule__Row__Group_6__0");
					put(grammarAccess.getRowAccess().getGroup_7(), "rule__Row__Group_7__0");
					put(grammarAccess.getRowAccess().getGroup_8(), "rule__Row__Group_8__0");
					put(grammarAccess.getRowAccess().getGroup_8_3(), "rule__Row__Group_8_3__0");
					put(grammarAccess.getHeaderAccess().getGroup(), "rule__Header__Group__0");
					put(grammarAccess.getHeaderAccess().getGroup_4(), "rule__Header__Group_4__0");
					put(grammarAccess.getHeaderAccess().getGroup_5(), "rule__Header__Group_5__0");
					put(grammarAccess.getHeaderAccess().getGroup_6(), "rule__Header__Group_6__0");
					put(grammarAccess.getHeaderAccess().getGroup_7(), "rule__Header__Group_7__0");
					put(grammarAccess.getHeaderAccess().getGroup_8(), "rule__Header__Group_8__0");
					put(grammarAccess.getHeaderAccess().getGroup_9(), "rule__Header__Group_9__0");
					put(grammarAccess.getParagrafAccess().getGroup(), "rule__Paragraf__Group__0");
					put(grammarAccess.getParagrafAccess().getGroup_4(), "rule__Paragraf__Group_4__0");
					put(grammarAccess.getParagrafAccess().getGroup_5(), "rule__Paragraf__Group_5__0");
					put(grammarAccess.getParagrafAccess().getGroup_6(), "rule__Paragraf__Group_6__0");
					put(grammarAccess.getParagrafAccess().getGroup_7(), "rule__Paragraf__Group_7__0");
					put(grammarAccess.getParagrafAccess().getGroup_8(), "rule__Paragraf__Group_8__0");
					put(grammarAccess.getCarouselAccess().getGroup(), "rule__Carousel__Group__0");
					put(grammarAccess.getCarouselAccess().getGroup_4(), "rule__Carousel__Group_4__0");
					put(grammarAccess.getCarouselAccess().getGroup_5(), "rule__Carousel__Group_5__0");
					put(grammarAccess.getCarouselAccess().getGroup_6(), "rule__Carousel__Group_6__0");
					put(grammarAccess.getCarouselAccess().getGroup_7(), "rule__Carousel__Group_7__0");
					put(grammarAccess.getCarouselAccess().getGroup_8(), "rule__Carousel__Group_8__0");
					put(grammarAccess.getCarouselAccess().getGroup_8_3(), "rule__Carousel__Group_8_3__0");
					put(grammarAccess.getImageAccess().getGroup(), "rule__Image__Group__0");
					put(grammarAccess.getImageAccess().getGroup_4(), "rule__Image__Group_4__0");
					put(grammarAccess.getImageAccess().getGroup_5(), "rule__Image__Group_5__0");
					put(grammarAccess.getImageAccess().getGroup_6(), "rule__Image__Group_6__0");
					put(grammarAccess.getImageAccess().getGroup_7(), "rule__Image__Group_7__0");
					put(grammarAccess.getImageAccess().getGroup_8(), "rule__Image__Group_8__0");
					put(grammarAccess.getImageAccess().getGroup_9(), "rule__Image__Group_9__0");
					put(grammarAccess.getCardAccess().getGroup(), "rule__Card__Group__0");
					put(grammarAccess.getCardAccess().getGroup_4(), "rule__Card__Group_4__0");
					put(grammarAccess.getCardAccess().getGroup_5(), "rule__Card__Group_5__0");
					put(grammarAccess.getCardAccess().getGroup_6(), "rule__Card__Group_6__0");
					put(grammarAccess.getCardAccess().getGroup_7(), "rule__Card__Group_7__0");
					put(grammarAccess.getCardAccess().getGroup_8(), "rule__Card__Group_8__0");
					put(grammarAccess.getCardAccess().getGroup_8_3(), "rule__Card__Group_8_3__0");
					put(grammarAccess.getAnchorAccess().getGroup(), "rule__Anchor__Group__0");
					put(grammarAccess.getAnchorAccess().getGroup_4(), "rule__Anchor__Group_4__0");
					put(grammarAccess.getAnchorAccess().getGroup_5(), "rule__Anchor__Group_5__0");
					put(grammarAccess.getAnchorAccess().getGroup_6(), "rule__Anchor__Group_6__0");
					put(grammarAccess.getAnchorAccess().getGroup_7(), "rule__Anchor__Group_7__0");
					put(grammarAccess.getAnchorAccess().getGroup_8(), "rule__Anchor__Group_8__0");
					put(grammarAccess.getAnchorAccess().getGroup_9(), "rule__Anchor__Group_9__0");
					put(grammarAccess.getAnchorAccess().getGroup_10(), "rule__Anchor__Group_10__0");
					put(grammarAccess.getDivisionAccess().getGroup(), "rule__Division__Group__0");
					put(grammarAccess.getDivisionAccess().getGroup_4(), "rule__Division__Group_4__0");
					put(grammarAccess.getDivisionAccess().getGroup_5(), "rule__Division__Group_5__0");
					put(grammarAccess.getDivisionAccess().getGroup_6(), "rule__Division__Group_6__0");
					put(grammarAccess.getDivisionAccess().getGroup_7(), "rule__Division__Group_7__0");
					put(grammarAccess.getDivisionAccess().getGroup_8(), "rule__Division__Group_8__0");
					put(grammarAccess.getDivisionAccess().getGroup_8_3(), "rule__Division__Group_8_3__0");
					put(grammarAccess.getMapAccess().getGroup(), "rule__Map__Group__0");
					put(grammarAccess.getMapAccess().getGroup_4(), "rule__Map__Group_4__0");
					put(grammarAccess.getMapAccess().getGroup_5(), "rule__Map__Group_5__0");
					put(grammarAccess.getMapAccess().getGroup_6(), "rule__Map__Group_6__0");
					put(grammarAccess.getMapAccess().getGroup_7(), "rule__Map__Group_7__0");
					put(grammarAccess.getMapAccess().getGroup_8(), "rule__Map__Group_8__0");
					put(grammarAccess.getMapAccess().getGroup_9(), "rule__Map__Group_9__0");
					put(grammarAccess.getCarouselPageAccess().getGroup(), "rule__CarouselPage__Group__0");
					put(grammarAccess.getCarouselPageAccess().getGroup_4(), "rule__CarouselPage__Group_4__0");
					put(grammarAccess.getCarouselPageAccess().getGroup_5(), "rule__CarouselPage__Group_5__0");
					put(grammarAccess.getCarouselPageAccess().getGroup_6(), "rule__CarouselPage__Group_6__0");
					put(grammarAccess.getCarouselPageAccess().getGroup_7(), "rule__CarouselPage__Group_7__0");
					put(grammarAccess.getCarouselPageAccess().getGroup_8(), "rule__CarouselPage__Group_8__0");
					put(grammarAccess.getCarouselPageAccess().getGroup_8_3(), "rule__CarouselPage__Group_8_3__0");
					put(grammarAccess.getCardPageAccess().getGroup(), "rule__CardPage__Group__0");
					put(grammarAccess.getCardPageAccess().getGroup_4(), "rule__CardPage__Group_4__0");
					put(grammarAccess.getCardPageAccess().getGroup_5(), "rule__CardPage__Group_5__0");
					put(grammarAccess.getCardPageAccess().getGroup_6(), "rule__CardPage__Group_6__0");
					put(grammarAccess.getCardPageAccess().getGroup_7(), "rule__CardPage__Group_7__0");
					put(grammarAccess.getCardPageAccess().getGroup_8(), "rule__CardPage__Group_8__0");
					put(grammarAccess.getCardPageAccess().getGroup_8_3(), "rule__CardPage__Group_8_3__0");
					put(grammarAccess.getMenuItemAccess().getGroup(), "rule__MenuItem__Group__0");
					put(grammarAccess.getMenuItemAccess().getGroup_4(), "rule__MenuItem__Group_4__0");
					put(grammarAccess.getMenuItemAccess().getGroup_5(), "rule__MenuItem__Group_5__0");
					put(grammarAccess.getMenuItemAccess().getGroup_6(), "rule__MenuItem__Group_6__0");
					put(grammarAccess.getMenuItemAccess().getGroup_7(), "rule__MenuItem__Group_7__0");
					put(grammarAccess.getMenuItemAccess().getGroup_8(), "rule__MenuItem__Group_8__0");
					put(grammarAccess.getMenuItemAccess().getGroup_9(), "rule__MenuItem__Group_9__0");
					put(grammarAccess.getModelAccess().getPageAssignment_3_1(), "rule__Model__PageAssignment_3_1");
					put(grammarAccess.getPageAccess().getTitleAssignment_3_1(), "rule__Page__TitleAssignment_3_1");
					put(grammarAccess.getPageAccess().getIntroSectionAssignment_4_1(), "rule__Page__IntroSectionAssignment_4_1");
					put(grammarAccess.getPageAccess().getSectionsAssignment_5_2(), "rule__Page__SectionsAssignment_5_2");
					put(grammarAccess.getPageAccess().getSectionsAssignment_5_3_1(), "rule__Page__SectionsAssignment_5_3_1");
					put(grammarAccess.getPageAccess().getMenuAssignment_6_1(), "rule__Page__MenuAssignment_6_1");
					put(grammarAccess.getSectionAccess().getNameAssignment_2(), "rule__Section__NameAssignment_2");
					put(grammarAccess.getSectionAccess().getColSpanAssignment_4_1(), "rule__Section__ColSpanAssignment_4_1");
					put(grammarAccess.getSectionAccess().getColorAssignment_5_1(), "rule__Section__ColorAssignment_5_1");
					put(grammarAccess.getSectionAccess().getBackgroundColorAssignment_6_1(), "rule__Section__BackgroundColorAssignment_6_1");
					put(grammarAccess.getSectionAccess().getBackgroundImageAssignment_7_1(), "rule__Section__BackgroundImageAssignment_7_1");
					put(grammarAccess.getSectionAccess().getElementsAssignment_8_2(), "rule__Section__ElementsAssignment_8_2");
					put(grammarAccess.getSectionAccess().getElementsAssignment_8_3_1(), "rule__Section__ElementsAssignment_8_3_1");
					put(grammarAccess.getMenuAccess().getNameAssignment_2(), "rule__Menu__NameAssignment_2");
					put(grammarAccess.getMenuAccess().getColSpanAssignment_4_1(), "rule__Menu__ColSpanAssignment_4_1");
					put(grammarAccess.getMenuAccess().getColorAssignment_5_1(), "rule__Menu__ColorAssignment_5_1");
					put(grammarAccess.getMenuAccess().getBackgroundColorAssignment_6_1(), "rule__Menu__BackgroundColorAssignment_6_1");
					put(grammarAccess.getMenuAccess().getBackgroundImageAssignment_7_1(), "rule__Menu__BackgroundImageAssignment_7_1");
					put(grammarAccess.getMenuAccess().getItemsAssignment_8_2(), "rule__Menu__ItemsAssignment_8_2");
					put(grammarAccess.getMenuAccess().getItemsAssignment_8_3_1(), "rule__Menu__ItemsAssignment_8_3_1");
					put(grammarAccess.getRowAccess().getNameAssignment_2(), "rule__Row__NameAssignment_2");
					put(grammarAccess.getRowAccess().getColSpanAssignment_4_1(), "rule__Row__ColSpanAssignment_4_1");
					put(grammarAccess.getRowAccess().getColorAssignment_5_1(), "rule__Row__ColorAssignment_5_1");
					put(grammarAccess.getRowAccess().getBackgroundColorAssignment_6_1(), "rule__Row__BackgroundColorAssignment_6_1");
					put(grammarAccess.getRowAccess().getBackgroundImageAssignment_7_1(), "rule__Row__BackgroundImageAssignment_7_1");
					put(grammarAccess.getRowAccess().getElementsAssignment_8_2(), "rule__Row__ElementsAssignment_8_2");
					put(grammarAccess.getRowAccess().getElementsAssignment_8_3_1(), "rule__Row__ElementsAssignment_8_3_1");
					put(grammarAccess.getHeaderAccess().getNameAssignment_2(), "rule__Header__NameAssignment_2");
					put(grammarAccess.getHeaderAccess().getColSpanAssignment_4_1(), "rule__Header__ColSpanAssignment_4_1");
					put(grammarAccess.getHeaderAccess().getColorAssignment_5_1(), "rule__Header__ColorAssignment_5_1");
					put(grammarAccess.getHeaderAccess().getBackgroundColorAssignment_6_1(), "rule__Header__BackgroundColorAssignment_6_1");
					put(grammarAccess.getHeaderAccess().getBackgroundImageAssignment_7_1(), "rule__Header__BackgroundImageAssignment_7_1");
					put(grammarAccess.getHeaderAccess().getTypeAssignment_8_1(), "rule__Header__TypeAssignment_8_1");
					put(grammarAccess.getHeaderAccess().getContentAssignment_9_1(), "rule__Header__ContentAssignment_9_1");
					put(grammarAccess.getParagrafAccess().getNameAssignment_2(), "rule__Paragraf__NameAssignment_2");
					put(grammarAccess.getParagrafAccess().getColSpanAssignment_4_1(), "rule__Paragraf__ColSpanAssignment_4_1");
					put(grammarAccess.getParagrafAccess().getColorAssignment_5_1(), "rule__Paragraf__ColorAssignment_5_1");
					put(grammarAccess.getParagrafAccess().getBackgroundColorAssignment_6_1(), "rule__Paragraf__BackgroundColorAssignment_6_1");
					put(grammarAccess.getParagrafAccess().getBackgroundImageAssignment_7_1(), "rule__Paragraf__BackgroundImageAssignment_7_1");
					put(grammarAccess.getParagrafAccess().getContentAssignment_8_1(), "rule__Paragraf__ContentAssignment_8_1");
					put(grammarAccess.getCarouselAccess().getNameAssignment_2(), "rule__Carousel__NameAssignment_2");
					put(grammarAccess.getCarouselAccess().getColSpanAssignment_4_1(), "rule__Carousel__ColSpanAssignment_4_1");
					put(grammarAccess.getCarouselAccess().getColorAssignment_5_1(), "rule__Carousel__ColorAssignment_5_1");
					put(grammarAccess.getCarouselAccess().getBackgroundColorAssignment_6_1(), "rule__Carousel__BackgroundColorAssignment_6_1");
					put(grammarAccess.getCarouselAccess().getBackgroundImageAssignment_7_1(), "rule__Carousel__BackgroundImageAssignment_7_1");
					put(grammarAccess.getCarouselAccess().getCarouselPagesAssignment_8_2(), "rule__Carousel__CarouselPagesAssignment_8_2");
					put(grammarAccess.getCarouselAccess().getCarouselPagesAssignment_8_3_1(), "rule__Carousel__CarouselPagesAssignment_8_3_1");
					put(grammarAccess.getImageAccess().getNameAssignment_2(), "rule__Image__NameAssignment_2");
					put(grammarAccess.getImageAccess().getColSpanAssignment_4_1(), "rule__Image__ColSpanAssignment_4_1");
					put(grammarAccess.getImageAccess().getColorAssignment_5_1(), "rule__Image__ColorAssignment_5_1");
					put(grammarAccess.getImageAccess().getBackgroundColorAssignment_6_1(), "rule__Image__BackgroundColorAssignment_6_1");
					put(grammarAccess.getImageAccess().getBackgroundImageAssignment_7_1(), "rule__Image__BackgroundImageAssignment_7_1");
					put(grammarAccess.getImageAccess().getSrcAssignment_8_1(), "rule__Image__SrcAssignment_8_1");
					put(grammarAccess.getImageAccess().getBorderRadiusAssignment_9_1(), "rule__Image__BorderRadiusAssignment_9_1");
					put(grammarAccess.getCardAccess().getNameAssignment_2(), "rule__Card__NameAssignment_2");
					put(grammarAccess.getCardAccess().getColSpanAssignment_4_1(), "rule__Card__ColSpanAssignment_4_1");
					put(grammarAccess.getCardAccess().getColorAssignment_5_1(), "rule__Card__ColorAssignment_5_1");
					put(grammarAccess.getCardAccess().getBackgroundColorAssignment_6_1(), "rule__Card__BackgroundColorAssignment_6_1");
					put(grammarAccess.getCardAccess().getBackgroundImageAssignment_7_1(), "rule__Card__BackgroundImageAssignment_7_1");
					put(grammarAccess.getCardAccess().getPagesAssignment_8_2(), "rule__Card__PagesAssignment_8_2");
					put(grammarAccess.getCardAccess().getPagesAssignment_8_3_1(), "rule__Card__PagesAssignment_8_3_1");
					put(grammarAccess.getAnchorAccess().getNameAssignment_2(), "rule__Anchor__NameAssignment_2");
					put(grammarAccess.getAnchorAccess().getColSpanAssignment_4_1(), "rule__Anchor__ColSpanAssignment_4_1");
					put(grammarAccess.getAnchorAccess().getColorAssignment_5_1(), "rule__Anchor__ColorAssignment_5_1");
					put(grammarAccess.getAnchorAccess().getBackgroundColorAssignment_6_1(), "rule__Anchor__BackgroundColorAssignment_6_1");
					put(grammarAccess.getAnchorAccess().getBackgroundImageAssignment_7_1(), "rule__Anchor__BackgroundImageAssignment_7_1");
					put(grammarAccess.getAnchorAccess().getTitleAssignment_8_1(), "rule__Anchor__TitleAssignment_8_1");
					put(grammarAccess.getAnchorAccess().getLinkAssignment_9_1(), "rule__Anchor__LinkAssignment_9_1");
					put(grammarAccess.getAnchorAccess().getTypeAssignment_10_1(), "rule__Anchor__TypeAssignment_10_1");
					put(grammarAccess.getDivisionAccess().getNameAssignment_2(), "rule__Division__NameAssignment_2");
					put(grammarAccess.getDivisionAccess().getColSpanAssignment_4_1(), "rule__Division__ColSpanAssignment_4_1");
					put(grammarAccess.getDivisionAccess().getColorAssignment_5_1(), "rule__Division__ColorAssignment_5_1");
					put(grammarAccess.getDivisionAccess().getBackgroundColorAssignment_6_1(), "rule__Division__BackgroundColorAssignment_6_1");
					put(grammarAccess.getDivisionAccess().getBackgroundImageAssignment_7_1(), "rule__Division__BackgroundImageAssignment_7_1");
					put(grammarAccess.getDivisionAccess().getElementsAssignment_8_2(), "rule__Division__ElementsAssignment_8_2");
					put(grammarAccess.getDivisionAccess().getElementsAssignment_8_3_1(), "rule__Division__ElementsAssignment_8_3_1");
					put(grammarAccess.getMapAccess().getNameAssignment_2(), "rule__Map__NameAssignment_2");
					put(grammarAccess.getMapAccess().getColSpanAssignment_4_1(), "rule__Map__ColSpanAssignment_4_1");
					put(grammarAccess.getMapAccess().getColorAssignment_5_1(), "rule__Map__ColorAssignment_5_1");
					put(grammarAccess.getMapAccess().getBackgroundColorAssignment_6_1(), "rule__Map__BackgroundColorAssignment_6_1");
					put(grammarAccess.getMapAccess().getBackgroundImageAssignment_7_1(), "rule__Map__BackgroundImageAssignment_7_1");
					put(grammarAccess.getMapAccess().getXAssignment_8_1(), "rule__Map__XAssignment_8_1");
					put(grammarAccess.getMapAccess().getYAssignment_9_1(), "rule__Map__YAssignment_9_1");
					put(grammarAccess.getCarouselPageAccess().getNameAssignment_2(), "rule__CarouselPage__NameAssignment_2");
					put(grammarAccess.getCarouselPageAccess().getColSpanAssignment_4_1(), "rule__CarouselPage__ColSpanAssignment_4_1");
					put(grammarAccess.getCarouselPageAccess().getColorAssignment_5_1(), "rule__CarouselPage__ColorAssignment_5_1");
					put(grammarAccess.getCarouselPageAccess().getBackgroundColorAssignment_6_1(), "rule__CarouselPage__BackgroundColorAssignment_6_1");
					put(grammarAccess.getCarouselPageAccess().getBackgroundImageAssignment_7_1(), "rule__CarouselPage__BackgroundImageAssignment_7_1");
					put(grammarAccess.getCarouselPageAccess().getElementsAssignment_8_2(), "rule__CarouselPage__ElementsAssignment_8_2");
					put(grammarAccess.getCarouselPageAccess().getElementsAssignment_8_3_1(), "rule__CarouselPage__ElementsAssignment_8_3_1");
					put(grammarAccess.getCardPageAccess().getNameAssignment_2(), "rule__CardPage__NameAssignment_2");
					put(grammarAccess.getCardPageAccess().getColSpanAssignment_4_1(), "rule__CardPage__ColSpanAssignment_4_1");
					put(grammarAccess.getCardPageAccess().getColorAssignment_5_1(), "rule__CardPage__ColorAssignment_5_1");
					put(grammarAccess.getCardPageAccess().getBackgroundColorAssignment_6_1(), "rule__CardPage__BackgroundColorAssignment_6_1");
					put(grammarAccess.getCardPageAccess().getBackgroundImageAssignment_7_1(), "rule__CardPage__BackgroundImageAssignment_7_1");
					put(grammarAccess.getCardPageAccess().getElementsAssignment_8_2(), "rule__CardPage__ElementsAssignment_8_2");
					put(grammarAccess.getCardPageAccess().getElementsAssignment_8_3_1(), "rule__CardPage__ElementsAssignment_8_3_1");
					put(grammarAccess.getMenuItemAccess().getNameAssignment_2(), "rule__MenuItem__NameAssignment_2");
					put(grammarAccess.getMenuItemAccess().getColSpanAssignment_4_1(), "rule__MenuItem__ColSpanAssignment_4_1");
					put(grammarAccess.getMenuItemAccess().getColorAssignment_5_1(), "rule__MenuItem__ColorAssignment_5_1");
					put(grammarAccess.getMenuItemAccess().getBackgroundColorAssignment_6_1(), "rule__MenuItem__BackgroundColorAssignment_6_1");
					put(grammarAccess.getMenuItemAccess().getBackgroundImageAssignment_7_1(), "rule__MenuItem__BackgroundImageAssignment_7_1");
					put(grammarAccess.getMenuItemAccess().getTitleAssignment_8_1(), "rule__MenuItem__TitleAssignment_8_1");
					put(grammarAccess.getMenuItemAccess().getSectionAssignment_9_1(), "rule__MenuItem__SectionAssignment_9_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.yazgel.aphrodit.xtext.ui.contentassist.antlr.internal.InternalAphroditParser typedParser = (org.yazgel.aphrodit.xtext.ui.contentassist.antlr.internal.InternalAphroditParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AphroditGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AphroditGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
