/*
 * generated by Xtext
 */
package org.yazgel.aphrodit.xtext.ui.contentassist

import org.yazgel.aphrodit.xtext.ui.contentassist.AbstractAphroditProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class AphroditProposalProvider extends AbstractAphroditProposalProvider {
}
