/*
 * generated by Xtext
 */
package org.yazgel.aphrodit.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.yazgel.aphrodit.xtext.ui.internal.AphroditActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AphroditExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AphroditActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AphroditActivator.getInstance().getInjector(AphroditActivator.ORG_YAZGEL_APHRODIT_XTEXT_APHRODIT);
	}
	
}
