/*
* generated by Xtext
*/
package org.yazgel.aphrodit.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.yazgel.aphrodit.xtext.services.AphroditGrammarAccess;

public class AphroditParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AphroditGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.yazgel.aphrodit.xtext.parser.antlr.internal.InternalAphroditParser createParser(XtextTokenStream stream) {
		return new org.yazgel.aphrodit.xtext.parser.antlr.internal.InternalAphroditParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public AphroditGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AphroditGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
