/*
* generated by Xtext
*/
package org.yazgel.aphrodit.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AphroditAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/yazgel/aphrodit/xtext/parser/antlr/internal/InternalAphrodit.tokens");
	}
}
