/*
 * generated by Xtext
 */
package org.yazgel.aphrodit.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AphroditUiModule extends org.yazgel.aphrodit.xtext.ui.AbstractAphroditUiModule {
	public AphroditUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
