/*
 * generated by Xtext
 */
package org.yazgel.aphrodit.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AphroditRuntimeModule extends org.yazgel.aphrodit.xtext.AbstractAphroditRuntimeModule {

}
